// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using to_do_api.Data;

#nullable disable

namespace to_do_api.Migrations
{
  [DbContext(typeof(ToDoContext))]
  partial class ToDoContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

      modelBuilder.Entity("to_do_api.Models.ToDoItem", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("INTEGER");

            b.Property<bool>("IsCompleted")
                      .HasColumnType("INTEGER");

            b.Property<string>("Title")
                      .IsRequired()
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("ToDoItems");
          });
#pragma warning restore 612, 618
    }
  }
}
